### ISSUE TITLE
Please remove Derek app from your org

### ISSUE THREAD

**Issue by alexellis** [Paperspace/gpt-2#1]
Hi 👋 since you are not actually using, Derek please could you remove the integration from your organisation? The bot is getting a lot of unnecessary messages from your organisation. You can remove it at: https://github.com/settings/installations

Someone may have installed Derek onto your whole GitHub org.

Derek -> github.com/alexellis/derek

We are getting lots of pings from a "PS_WEB" repo.

Feel free to email me alex@openfaas.com

I emailed hello@ in March and received no reply.

Alex

**Comment by mikuts** [comment]
hey @alexellis thanks reporting this - uninstalled the Derek app from our org. apologies for any spam that this caused.

**Comment by alexellis** [comment]
Since you're not using Derek (but are of course welcome to do so) would you mind removing it from the whole org?
